version: "3"
services:
  sqlite:
    container_name: fastmoni-container
    image: sqlite:latest
    volumes:
      - sqlite-data:/fastmoni
    ports:
      - "5432:5432"
    restart: always

volumes:
  sqlite-data:
